slurp = {
  "$type": "Models.Core.Simulations, Models",
  "ExplorerWidth": 282,
  "Version": 85,
  "ApsimVersion": "0.0.0.0",
  "Name": "Simulations",
  "Children": [
    {
      "$type": "Models.Storage.DataStore, Models",
      "useFirebird": False,
      "CustomFileName": None,
      "Name": "DataStore",
      "Children": [
        {
          "$type": "Models.PostSimulationTools.ExcelInput, Models",
          "FileNames": [
            "%root%\\Tests\\Validation\\Slurp\\ShallowSoilTest\\SoilWaterContent.xlsx"
          ],
          "SheetNames": [
            "ProfileSWC"
          ],
          "Name": "ProfileSWC",
          "Children": [],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.PostSimulationTools.ExcelInput, Models",
          "FileNames": [
            "%root%\\Tests\\Validation\\Slurp\\ShallowSoilTest\\SoilWaterContent.xlsx"
          ],
          "SheetNames": [
            "LayerSWC"
          ],
          "Name": "LayerSWC",
          "Children": [],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.PostSimulationTools.ExcelInput, Models",
          "FileNames": [
            "%root%\\Tests\\Validation\\Slurp\\ShallowSoilTest\\CoverDataObs.xlsx"
          ],
          "SheetNames": [
            "Cover"
          ],
          "Name": "Cover",
          "Children": [],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.PostSimulationTools.Input, Models",
          "FileNames": [
            "%root%\\Tests\\Validation\\Slurp\\ShallowSoilTest\\CoverInterpolated.csv"
          ],
          "Name": "Input",
          "Children": [],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.PostSimulationTools.PredictedObserved, Models",
          "PredictedTableName": "Report",
          "ObservedTableName": "ProfileSWC",
          "FieldNameUsedForMatch": "Clock.Today",
          "FieldName2UsedForMatch": None,
          "FieldName3UsedForMatch": None,
          "Name": "ProfileWater",
          "Children": [
            {
              "$type": "Models.Tests, Models",
              "AcceptedStats": [
                {
                  "$type": "APSIM.Shared.Utilities.MathUtilities+RegrStats, APSIM.Shared",
                  "Name": "PSWC",
                  "n": 448,
                  "Slope": 0.75529467401224393,
                  "Intercept": 46.641922387743136,
                  "SEslope": 0.032635564267904586,
                  "SEintercept": 7.3221726777587319,
                  "R2": 0.54564549406362484,
                  "RMSE": 34.830827822681485,
                  "NSE": 0.44216532820903054,
                  "ME": -7.0614956234619486,
                  "MAE": 26.92381385501173,
                  "RSR": 0.74604926453476561
                }
              ],
              "AcceptedStatsName": "Name n Slope Intercept SEslope SEintercept R2 RMSE NSE ME MAE RSR",
              "POName": "ProfileWater",
              "Name": "Tests",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            }
          ],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.PostSimulationTools.PredictedObserved, Models",
          "PredictedTableName": "Report",
          "ObservedTableName": "Cover",
          "FieldNameUsedForMatch": "Clock.Today",
          "FieldName2UsedForMatch": None,
          "FieldName3UsedForMatch": None,
          "Name": "CanopyCover",
          "Children": [
            {
              "$type": "Models.Tests, Models",
              "AcceptedStats": [
                {
                  "$type": "APSIM.Shared.Utilities.MathUtilities+RegrStats, APSIM.Shared",
                  "Name": "Slurp.Leaf.CoverTotal",
                  "n": 824,
                  "Slope": 1.0135080689834304,
                  "Intercept": -0.041930843368039983,
                  "SEslope": 0.007032305650724744,
                  "SEintercept": 0.005566810818574775,
                  "R2": 0.96193223734531108,
                  "RMSE": 0.068422625244649649,
                  "NSE": 0.94770680215271219,
                  "ME": -0.032031059935304196,
                  "MAE": 0.03311722682985576,
                  "RSR": 0.22853825769122579
                }
              ],
              "AcceptedStatsName": "Name n Slope Intercept SEslope SEintercept R2 RMSE NSE ME MAE RSR",
              "POName": "CanopyCover",
              "Name": "Tests",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            }
          ],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        }
      ],
      "IncludeInDocumentation": False,
      "Enabled": True,
      "ReadOnly": False
    },
    {
      "$type": "Models.Core.Simulation, Models",
      "Name": "SlurpExample",
      "Children": [
        {
          "$type": "Models.Memo, Models",
          "Text": "This is a simple test that plants SLURP, changes its leaf area index and potential biomass production on one occasion and presents some graphs of Plant, N and Water balance components to show things are working.",
          "Name": "Memo",
          "Children": [],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.Weather, Models",
          "FileName": "%root%\\Examples\\WeatherFiles\\lincoln.met",
          "ExcelWorkSheetName": None,
          "Name": "Weather",
          "Children": [],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.Clock, Models",
          "Start": "1998-10-14T00:00:00",
          "End": "1999-05-01T00:00:00",
          "Name": "Clock",
          "Children": [],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.Summary, Models",
          "CaptureErrors": True,
          "CaptureWarnings": True,
          "CaptureSummaryText": True,
          "Name": "Summary",
          "Children": [],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.Soils.Arbitrator.SoilArbitrator, Models",
          "Name": "Soil Arbitrator",
          "Children": [],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.Core.Zone, Models",
          "Area": 1.0,
          "Slope": 0.0,
          "AspectAngle": 0.0,
          "Altitude": 50.0,
          "Name": "Field",
          "Children": [
            {
              "$type": "Models.Soils.Soil, Models",
              "RecordNumber": 0,
              "ASCOrder": None,
              "ASCSubOrder": None,
              "SoilType": None,
              "LocalName": None,
              "Site": None,
              "NearestTown": None,
              "Region": None,
              "State": None,
              "Country": None,
              "NaturalVegetation": None,
              "ApsoilNumber": None,
              "Latitude": 0.0,
              "Longitude": 0.0,
              "LocationAccuracy": None,
              "DataSource": None,
              "Comments": None,
              "Name": "Soil",
              "Children": [
                {
                  "$type": "Models.Soils.Chemical, Models",
                  "Depth": [
                    "0-10",
                    "10-30",
                    "30-60",
                    "60-90",
                    "90-120",
                    "120-150"
                  ],
                  "Thickness": [
                    100.0,
                    200.0,
                    300.0,
                    300.0,
                    300.0,
                    300.0
                  ],
                  "NO3N": [
                    14.166666666666664,
                    12.5,
                    1.3888888888888884,
                    1.38888888888889,
                    0.0,
                    0.0
                  ],
                  "NH4N": [
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0
                  ],
                  "PH": [
                    6.6,
                    6.2,
                    5.7,
                    5.5,
                    5.5,
                    5.5
                  ],
                  "CL": None,
                  "EC": None,
                  "ESP": None,
                  "Name": "Chemical",
                  "Children": [],
                  "IncludeInDocumentation": False,
                  "Enabled": True,
                  "ReadOnly": False
                },
                {
                  "$type": "Models.Soils.InitialWater, Models",
                  "PercentMethod": 1,
                  "FractionFull": 1.0,
                  "DepthWetSoil": "NaN",
                  "RelativeTo": None,
                  "Name": "Initial water",
                  "Children": [],
                  "IncludeInDocumentation": False,
                  "Enabled": True,
                  "ReadOnly": False
                },
                {
                  "$type": "Models.Soils.Physical, Models",
                  "Depth": [
                    "0-10",
                    "10-30",
                    "30-60",
                    "60-90",
                    "90-120",
                    "120-150"
                  ],
                  "Thickness": [
                    100.0,
                    200.0,
                    300.0,
                    300.0,
                    300.0,
                    300.0
                  ],
                  "ParticleSizeClay": None,
                  "ParticleSizeSand": None,
                  "ParticleSizeSilt": None,
                  "BD": [
                    1.2,
                    1.2,
                    1.2,
                    1.2,
                    1.2,
                    1.2
                  ],
                  "AirDry": [
                    0.08,
                    0.13,
                    0.1,
                    0.06,
                    0.04,
                    0.02
                  ],
                  "LL15": [
                    0.13,
                    0.13,
                    0.1,
                    0.06,
                    0.04,
                    0.02
                  ],
                  "DUL": [
                    0.33,
                    0.33,
                    0.31,
                    0.3,
                    0.3,
                    0.3
                  ],
                  "SAT": [
                    0.5,
                    0.5,
                    0.44,
                    0.46,
                    0.44,
                    0.44
                  ],
                  "KS": None,
                  "BDMetadata": None,
                  "AirDryMetadata": None,
                  "LL15Metadata": None,
                  "DULMetadata": None,
                  "SATMetadata": None,
                  "KSMetadata": None,
                  "Name": "Physical",
                  "Children": [
                    {
                      "$type": "Models.Soils.SoilCrop, Models",
                      "LL": [
                        0.13,
                        0.13,
                        0.1,
                        0.08,
                        0.11,
                        0.11
                      ],
                      "KL": [
                        0.06,
                        0.06,
                        0.06,
                        0.06,
                        0.06,
                        0.06
                      ],
                      "XF": [
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0
                      ],
                      "LLMetadata": None,
                      "KLMetadata": None,
                      "XFMetadata": None,
                      "Name": "SlurpSoil",
                      "Children": [],
                      "IncludeInDocumentation": False,
                      "Enabled": True,
                      "ReadOnly": False
                    },
                    {
                      "$type": "Models.Soils.SoilCrop, Models",
                      "LL": [
                        0.13,
                        0.13,
                        0.27,
                        0.27,
                        0.3,
                        0.3
                      ],
                      "KL": [
                        0.1,
                        0.06,
                        0.03,
                        0.01,
                        0.0,
                        0.0
                      ],
                      "XF": [
                        1.0,
                        1.0,
                        0.1,
                        0.0,
                        0.0,
                        0.0
                      ],
                      "LLMetadata": None,
                      "KLMetadata": None,
                      "XFMetadata": None,
                      "Name": "PotatoSoil",
                      "Children": [],
                      "IncludeInDocumentation": False,
                      "Enabled": True,
                      "ReadOnly": False
                    }
                  ],
                  "IncludeInDocumentation": False,
                  "Enabled": True,
                  "ReadOnly": False
                },
                {
                  "$type": "Models.Soils.SoilWater, Models",
                  "SummerDate": "1-Nov",
                  "SummerU": 9.0,
                  "SummerCona": 4.4,
                  "WinterDate": "1-Apr",
                  "WinterU": 9.0,
                  "WinterCona": 4.4,
                  "DiffusConst": 88.0,
                  "DiffusSlope": 35.4,
                  "Salb": 0.18,
                  "CN2Bare": 68.0,
                  "CNRed": 20.0,
                  "CNCov": 0.8,
                  "slope": 0.0,
                  "discharge_width": 0.0,
                  "catchment_area": 0.0,
                  "max_pond": 0.0,
                  "Thickness": [
                    100.0,
                    200.0,
                    300.0,
                    300.0,
                    300.0,
                    300.0
                  ],
                  "Depth": [
                    "0-10",
                    "10-30",
                    "30-60",
                    "60-90",
                    "90-120",
                    "120-150"
                  ],
                  "SWCON": [
                    0.55,
                    0.55,
                    0.55,
                    0.55,
                    0.55,
                    0.55
                  ],
                  "KLAT": [
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0
                  ],
                  "PrecipitationInterception": 0.0,
                  "Name": "SoilWater",
                  "Children": [],
                  "IncludeInDocumentation": False,
                  "Enabled": True,
                  "ReadOnly": False
                },
                {
                  "$type": "Models.Soils.Organic, Models",
                  "Depth": [
                    "0-10",
                    "10-30",
                    "30-60",
                    "60-90",
                    "90-120",
                    "120-150"
                  ],
                  "FOMCNRatio": 30.0,
                  "Thickness": [
                    100.0,
                    200.0,
                    300.0,
                    300.0,
                    300.0,
                    300.0
                  ],
                  "Carbon": [
                    1.82,
                    1.47,
                    1.2,
                    1.03,
                    0.47,
                    0.47
                  ],
                  "SoilCNRatio": [
                    11.5,
                    11.5,
                    11.5,
                    11.5,
                    11.5,
                    11.5
                  ],
                  "FBiom": [
                    0.025,
                    0.025,
                    0.015,
                    0.01,
                    0.01,
                    0.01
                  ],
                  "FInert": [
                    0.3,
                    0.4,
                    0.75,
                    0.9,
                    0.96,
                    0.96
                  ],
                  "FOM": [
                    1243.9310541346904,
                    833.83192147272689,
                    457.61666105087295,
                    251.14534845521521,
                    137.83148958311097,
                    75.643525303383925
                  ],
                  "Name": "Organic",
                  "Children": [],
                  "IncludeInDocumentation": False,
                  "Enabled": True,
                  "ReadOnly": False
                },
                {
                  "$type": "Models.Soils.Sample, Models",
                  "Depth": [
                    "0-10",
                    "10-30",
                    "30-60",
                    "60-90",
                    "90-120",
                    "120-150"
                  ],
                  "Thickness": [
                    100.0,
                    200.0,
                    300.0,
                    300.0,
                    300.0,
                    300.0
                  ],
                  "NO3N": None,
                  "NH4N": None,
                  "SW": None,
                  "OC": None,
                  "EC": None,
                  "CL": None,
                  "ESP": None,
                  "PH": None,
                  "SWUnits": 0,
                  "OCUnits": 0,
                  "PHUnits": 0,
                  "Name": "Initial nitrogen",
                  "Children": [],
                  "IncludeInDocumentation": False,
                  "Enabled": True,
                  "ReadOnly": False
                },
                {
                  "$type": "Models.Soils.CERESSoilTemperature, Models",
                  "Name": "CERESSoilTemperature",
                  "Children": [],
                  "IncludeInDocumentation": False,
                  "Enabled": True,
                  "ReadOnly": False
                },
                {
                  "$type": "Models.Soils.Nutrients.Nutrient, Models",
                  "DirectedGraphInfo": {
                    "$type": "Models.Graph.DirectedGraph, Models",
                    "Nodes": [
                      {
                        "$type": "Models.Graph.Node, Models",
                        "Name": "Inert",
                        "Location": "656, 254",
                        "Colour": "0, 114, 178",
                        "OutlineColour": "Black",
                        "Transparent": False
                      },
                      {
                        "$type": "Models.Graph.Node, Models",
                        "Name": "SurfaceResidue",
                        "Location": "566, 69",
                        "Colour": "0, 114, 178",
                        "OutlineColour": "Black",
                        "Transparent": False
                      },
                      {
                        "$type": "Models.Graph.Node, Models",
                        "Name": "FOMLignin",
                        "Location": "261, 69",
                        "Colour": "0, 114, 178",
                        "OutlineColour": "Black",
                        "Transparent": False
                      },
                      {
                        "$type": "Models.Graph.Node, Models",
                        "Name": "FOMCellulose",
                        "Location": "397, 70",
                        "Colour": "0, 114, 178",
                        "OutlineColour": "Black",
                        "Transparent": False
                      },
                      {
                        "$type": "Models.Graph.Node, Models",
                        "Name": "FOMCarbohydrate",
                        "Location": "123, 70",
                        "Colour": "0, 114, 178",
                        "OutlineColour": "Black",
                        "Transparent": False
                      },
                      {
                        "$type": "Models.Graph.Node, Models",
                        "Name": "Microbial",
                        "Location": "218, 299",
                        "Colour": "0, 114, 178",
                        "OutlineColour": "Black",
                        "Transparent": False
                      },
                      {
                        "$type": "Models.Graph.Node, Models",
                        "Name": "Humic",
                        "Location": "458, 293",
                        "Colour": "0, 114, 178",
                        "OutlineColour": "Black",
                        "Transparent": False
                      },
                      {
                        "$type": "Models.Graph.Node, Models",
                        "Name": "Urea",
                        "Location": "529, 419",
                        "Colour": "0, 158, 115",
                        "OutlineColour": "Black",
                        "Transparent": False
                      },
                      {
                        "$type": "Models.Graph.Node, Models",
                        "Name": "NO3",
                        "Location": "185, 435",
                        "Colour": "0, 158, 115",
                        "OutlineColour": "Black",
                        "Transparent": False
                      },
                      {
                        "$type": "Models.Graph.Node, Models",
                        "Name": "NH4",
                        "Location": "357, 422",
                        "Colour": "0, 158, 115",
                        "OutlineColour": "Black",
                        "Transparent": False
                      },
                      {
                        "$type": "Models.Graph.Node, Models",
                        "Name": "Atmosphere",
                        "Location": "48, 338",
                        "Colour": "White",
                        "OutlineColour": "White",
                        "Transparent": True
                      }
                    ],
                    "Arcs": [
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "SurfaceResidue",
                        "DestinationName": "Microbial",
                        "Location": "415, 173",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "SurfaceResidue",
                        "DestinationName": "Humic",
                        "Location": "499, 172",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "FOMLignin",
                        "DestinationName": "Microbial",
                        "Location": "259, 221",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "FOMLignin",
                        "DestinationName": "Humic",
                        "Location": "255, 105",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "FOMCellulose",
                        "DestinationName": "Microbial",
                        "Location": "370, 184",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "FOMCellulose",
                        "DestinationName": "Humic",
                        "Location": "463, 224",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "FOMCarbohydrate",
                        "DestinationName": "Microbial",
                        "Location": "141, 131",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "FOMCarbohydrate",
                        "DestinationName": "Humic",
                        "Location": "204, 215",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "Microbial",
                        "DestinationName": "Microbial",
                        "Location": "335, 301",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "Microbial",
                        "DestinationName": "Humic",
                        "Location": "319, 278",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "Humic",
                        "DestinationName": "Microbial",
                        "Location": "334, 340",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "Urea",
                        "DestinationName": "NH4",
                        "Location": "433, 416",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "NO3",
                        "DestinationName": "Atmosphere",
                        "Location": "1, 319",
                        "Colour": "Black",
                        "Text": None
                      },
                      {
                        "$type": "Models.Graph.Arc, Models",
                        "SourceName": "NH4",
                        "DestinationName": "NO3",
                        "Location": "243, 409",
                        "Colour": "Black",
                        "Text": None
                      }
                    ]
                  },
                  "ResourceName": "Nutrient",
                  "Name": "Nutrient",
                  "IncludeInDocumentation": True,
                  "Enabled": True,
                  "ReadOnly": False
                }
              ],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.PMF.Plant, Models",
              "CropType": "Slurp",
              "IsAlive": False,
              "IsEnding": False,
              "DaysAfterEnding": 0,
              "ResourceName": "Slurp",
              "Name": "Slurp",
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.MicroClimate, Models",
              "a_interception": 0.0,
              "b_interception": 1.0,
              "c_interception": 0.0,
              "d_interception": 0.0,
              "soil_albedo": 0.23,
              "SoilHeatFluxFraction": 0.4,
              "MinimumHeightDiffForNewLayer": 0.0,
              "NightInterceptionFraction": 0.5,
              "ReferenceHeight": 2.0,
              "Name": "MicroClimate",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Irrigation, Models",
              "Name": "Irrigation",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Fertiliser, Models",
              "Name": "Fertiliser",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Manager, Models",
              "Code": "\r\nusing System;\r\nusing Models.Core;\r\nusing Models.PMF;\r\nusing APSIM.Shared.Utilities;\r\n        \r\nnamespace Models\r\n{\r\n    [Serializable] \r\n    [System.Xml.Serialization.XmlInclude(typeof(Model))]\r\n    public class Script : Model\r\n    {\r\n        [Link] Plant Slurp;\r\n        [Link] Clock Clock;\r\n\r\n        [Description(\"Cultivar\")]\r\n        [Display(Type=DisplayType.CultivarName, PlantName = \"Slurp\")]\r\n        public string CultivarName { get; set; }\r\n        [Description(\"Initial Root Depth\")]\r\n        public double InitialRootDepth { get; set; }\r\n        [Description(\"Sowing Date\")]\r\n        public DateTime SowingDate { get; set; }\r\n\r\n               \r\n        [EventSubscribe(\"DoManagement\")]\r\n        private void OnDoManagement(object sender, EventArgs e)\r\n        {\r\n            if (Clock.Today.Date == SowingDate)\r\n                Slurp.Sow(cultivar: CultivarName, population: 1, depth: InitialRootDepth, rowSpacing: 150);\r\n            //Potato.Sow(... Contains the following arguements:\r\n            //Population  double  Optional  Seeds sowing/m2.  Default is zero\r\n            //Cultivar    string  Required  \"NameOfCultivar\"\r\n            //Depth       double  Optional  Depth (mm) seed sown.   Default is 100mm \r\n            //MaxCover    double  Optional  Proportion (0-1) of the ground row crop will cover.   Default is 1.0\r\n            //BudNumber   double  Optional  Number of mainstems per seed sown.  Default is 1.0\r\n            //RowSpacing  double  Optional  Spaceing (mm) between drill rows when crop is sown.  Default is 150mm\r\n            //CropClass   string  Optional  Crop class to instantiate when crop is sown.  Default is \"Plant\"\r\n        }\r\n    }\r\n}\r\n                \r\n",
              "Parameters": [
                {
                  "Key": "CultivarName",
                  "Value": "StaticCrop"
                },
                {
                  "Key": "InitialRootDepth",
                  "Value": "600"
                },
                {
                  "Key": "SowingDate",
                  "Value": "10/14/1998 00:00:00"
                }
              ],
              "Name": "SlurpSowingRule",
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Surface.SurfaceOrganicMatter, Models",
              "Canopies": [],
              "InitialResidueName": "wheat",
              "InitialResidueType": "wheat",
              "InitialResidueMass": 2000.0,
              "InitialStandingFraction": 0.0,
              "InitialCPR": 0.0,
              "InitialCNR": 80.0,
              "FractionFaecesAdded": 1.0,
              "ResourceName": "SurfaceOrganicMatter",
              "Name": "surface organic matter",
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Operations, Models",
              "Operation": [
                {
                  "$type": "Models.Operation, Models",
                  "Date": "1998-10-02T00:00:00",
                  "Action": "[Irrigation].Apply(40);",
                  "Enabled": True
                },
                {
                  "$type": "Models.Operation, Models",
                  "Date": "1998-10-26T00:00:00",
                  "Action": "[Irrigation].Apply(70);",
                  "Enabled": True
                },
                {
                  "$type": "Models.Operation, Models",
                  "Date": "1998-12-15T00:00:00",
                  "Action": "[Irrigation].Apply(70);",
                  "Enabled": True
                },
                {
                  "$type": "Models.Operation, Models",
                  "Date": "1998-12-29T00:00:00",
                  "Action": "[Irrigation].Apply(10);",
                  "Enabled": True
                },
                {
                  "$type": "Models.Operation, Models",
                  "Date": "1998-12-30T00:00:00",
                  "Action": "[Irrigation].Apply(55);",
                  "Enabled": True
                },
                {
                  "$type": "Models.Operation, Models",
                  "Date": "1999-01-07T00:00:00",
                  "Action": "[Irrigation].Apply(50);",
                  "Enabled": True
                },
                {
                  "$type": "Models.Operation, Models",
                  "Date": "1999-01-21T00:00:00",
                  "Action": "[Irrigation].Apply(40);",
                  "Enabled": True
                },
                {
                  "$type": "Models.Operation, Models",
                  "Date": "1999-02-10T00:00:00",
                  "Action": "[Irrigation].Apply(28);",
                  "Enabled": True
                },
                {
                  "$type": "Models.Operation, Models",
                  "Date": "1999-02-19T00:00:00",
                  "Action": "[Irrigation].Apply(15);",
                  "Enabled": True
                },
                {
                  "$type": "Models.Operation, Models",
                  "Date": "1999-03-09T00:00:00",
                  "Action": "[Irrigation].Apply(25);",
                  "Enabled": True
                },
                {
                  "$type": "Models.Operation, Models",
                  "Date": "1998-12-29T00:00:00",
                  "Action": "[Fertiliser].Apply(50, Fertiliser.Types.UreaN, 10);",
                  "Enabled": True
                }
              ],
              "Name": "operations",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Report.Report, Models",
              "VariableNames": [
                "[Clock].Today",
                "[Slurp].Root.NUptake",
                "sum([Soil].Nutrient.MineralisedN) as Mineralisation",
                "sum([Soil].Nutrient.Natm) as Denitrification",
                "[Fertiliser].NitrogenApplied",
                "([Soil].SoilWater.LeachNH4 + [Soil].SoilWater.LeachNO3 + [Soil].SoilWater.LeachUrea) as Leach",
                "[Soil].SoilWater.Eo",
                "[Soil].SoilWater.Es",
                "[Soil].SoilWater.Drainage",
                "[Soil].SoilWater.Runoff",
                "[Soil].SoilWater.pond",
                "[Slurp].Root.WaterUptake",
                "[Weather].Rain",
                "[Irrigation].IrrigationApplied",
                "sum([Soil].SoilWater.SWmm) - sum([Soil].DULmm) as SoilWaterDeficit",
                "[Slurp].Leaf.Live.Wt",
                "[Slurp].Root.Live.Wt",
                "[Slurp].Leaf.Live.N",
                "[Slurp].Root.Live.N",
                "[Slurp].Leaf.Live.NConc",
                "[Slurp].Root.Live.NConc",
                "[Slurp].Leaf.Transpiration",
                "[Slurp].Leaf.WaterDemand",
                "[Slurp].Root.Depth",
                "[Slurp].Leaf.CoverTotal",
                "[Slurp].Leaf.CoverDead",
                "[Slurp].Leaf.LAI",
                "[Slurp].Leaf.Height",
                "[Slurp].Leaf.Fw",
                "[Slurp].Leaf.Fn"
              ],
              "EventNames": [
                "[Clock].DoReport"
              ],
              "Name": "Report",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            }
          ],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.Graph.Graph, Models",
          "Caption": None,
          "Axis": [
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 3,
              "Title": "X axis title 2",
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            },
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 0,
              "Title": "Accumulated N changes (kg/ha)",
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            }
          ],
          "LegendPosition": 2,
          "LegendOrientation": 0,
          "DisabledSeries": None,
          "LegendOutsideGraph": False,
          "Name": "N balance components",
          "Children": [
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16736653,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Slurp.Root.NUptake",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumPlantN",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -1663232,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Mineralisation",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumMineralisation",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -11094807,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Denitrification",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumDenit",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16747854,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Fertiliser.NitrogenApplied",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumFert",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -2793984,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Leach",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumLeach",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            }
          ],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.Graph.Graph, Models",
          "Caption": None,
          "Axis": [
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 0,
              "Title": "Accumulated Water Changes (mm)",
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            },
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 3,
              "Title": None,
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            }
          ],
          "LegendPosition": 2,
          "LegendOrientation": 0,
          "DisabledSeries": None,
          "LegendOutsideGraph": False,
          "Name": "WaterBalanceComponents",
          "Children": [
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16777216,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Soil.SoilWater.Eo",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumEO",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -1663232,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Slurp.Leaf.Transpiration",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumEP",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16736653,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Soil.SoilWater.Es",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumES",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16747854,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Soil.SoilWater.Drainage",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumDrainage",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -2793984,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Soil.SoilWater.Runoff",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumRunoff",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -3376729,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Weather.Rain",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumRainfall",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -990142,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Irrigation.IrrigationApplied",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": True,
              "CumulativeX": False,
              "Filter": None,
              "Name": "AccumIrrigation",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16777216,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 1,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "SoilWaterDeficit",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": False,
              "CumulativeX": False,
              "Filter": None,
              "Name": "SoilWaterDeficit",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            }
          ],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.Graph.Graph, Models",
          "Caption": None,
          "Axis": [
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 0,
              "Title": "Crop Biomass (g/m2)",
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            },
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 3,
              "Title": None,
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            }
          ],
          "LegendPosition": 0,
          "LegendOrientation": 0,
          "DisabledSeries": None,
          "LegendOutsideGraph": False,
          "Name": "Plant Biomass components",
          "Children": [
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16736653,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Slurp.Leaf.Live.Wt",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": False,
              "CumulativeX": False,
              "Filter": None,
              "Name": "Leaf",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16777216,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Slurp.Root.Live.Wt",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": False,
              "CumulativeX": False,
              "Filter": None,
              "Name": "Root",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            }
          ],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.Graph.Graph, Models",
          "Caption": None,
          "Axis": [
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 0,
              "Title": "Crop Nitrogen (g/m2)",
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            },
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 3,
              "Title": None,
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            }
          ],
          "LegendPosition": 0,
          "LegendOrientation": 0,
          "DisabledSeries": None,
          "LegendOutsideGraph": False,
          "Name": "Plant Nitrogen components",
          "Children": [
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16736653,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Slurp.Leaf.Live.N",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": False,
              "CumulativeX": False,
              "Filter": None,
              "Name": "Leaf",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16777216,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Slurp.Root.Live.N",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": False,
              "CumulativeX": False,
              "Filter": None,
              "Name": "Root",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            }
          ],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.Graph.Graph, Models",
          "Caption": None,
          "Axis": [
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 0,
              "Title": "Cover and LAI",
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            },
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 3,
              "Title": None,
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            },
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 2,
              "Title": None,
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            }
          ],
          "LegendPosition": 1,
          "LegendOrientation": 0,
          "DisabledSeries": None,
          "LegendOutsideGraph": False,
          "Name": "Crop structure",
          "Children": [
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16736653,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Slurp.Leaf.CoverTotal",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": False,
              "CumulativeX": False,
              "Filter": None,
              "Name": "Cover Total",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -11094807,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Slurp.Leaf.LAI",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": False,
              "CumulativeX": False,
              "Filter": None,
              "Name": "LAI",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 2,
              "ColourArgb": -16777216,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Slurp.Root.Depth",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": False,
              "CumulativeX": False,
              "Filter": None,
              "Name": "RootDepth",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            }
          ],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        },
        {
          "$type": "Models.Graph.Graph, Models",
          "Caption": None,
          "Axis": [
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 0,
              "Title": "Water (mm)",
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            },
            {
              "$type": "Models.Graph.Axis, Models",
              "Type": 3,
              "Title": None,
              "Inverted": False,
              "Minimum": "NaN",
              "Maximum": "NaN",
              "Interval": "NaN",
              "DateTimeAxis": False,
              "CrossesAtZero": False
            }
          ],
          "LegendPosition": 0,
          "LegendOrientation": 0,
          "DisabledSeries": None,
          "LegendOutsideGraph": False,
          "Name": "Stress Factors",
          "Children": [
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -11094807,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Slurp.Leaf.Fw",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": False,
              "CumulativeX": False,
              "Filter": None,
              "Name": "FW",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            },
            {
              "$type": "Models.Graph.Series, Models",
              "Type": 1,
              "XAxis": 3,
              "YAxis": 0,
              "ColourArgb": -16736653,
              "FactorToVaryColours": None,
              "FactorToVaryMarkers": None,
              "FactorToVaryLines": None,
              "Marker": 11,
              "MarkerSize": 0,
              "Line": 0,
              "LineThickness": 0,
              "TableName": "Report",
              "XFieldName": "Clock.Today",
              "YFieldName": "Slurp.Leaf.Fn",
              "X2FieldName": "",
              "Y2FieldName": "",
              "ShowInLegend": True,
              "IncludeSeriesNameInLegend": True,
              "Cumulative": False,
              "CumulativeX": False,
              "Filter": None,
              "Name": "FN",
              "Children": [],
              "IncludeInDocumentation": False,
              "Enabled": True,
              "ReadOnly": False
            }
          ],
          "IncludeInDocumentation": False,
          "Enabled": True,
          "ReadOnly": False
        }
      ],
      "IncludeInDocumentation": False,
      "Enabled": True,
      "ReadOnly": False
    }
  ],
  "IncludeInDocumentation": True,
  "Enabled": True,
  "ReadOnly": False
}