{% set data = load_setup_py_data() %}

package:
  name: pycropml
  version: {{ data.get('version') }}

source:
  path: ..

build:
  #noarch: python  [unix]
  preserve_egg_dir: True
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry: 
    - cyml = pycropml.main:main

requirements:
  build:
    - python {{PY_VER}}
    - pip
    - setuptools
  run:
    - python {{PY_VER}}
    - antlr4-python3-runtime  ==4.8
    - cython >=0.29.37,<3
    - xmlformatter
    - path
    {% if PY_VER.startswith("3.9") %}
    - numpy ==2.0.2   # For Python 3.9
    {% elif PY_VER.startswith("3.10") %}
    - numpy ==2.0.2   # For Python 3.10
    {% elif PY_VER.startswith("3.11") %}
    - numpy ==2.0.2   # For Python 3.11
    {% endif %}
    - pyyaml
    - six
    - networkx
    - unyt
    - nbformat
    - ipython
    - nbsphinx
    - graphviz
    - pydot
    - openalea.core


#test:
#  imports:
#    - pycropml

about:
  home: https://github.com/AgriculturalModelExchangeInitiative/PyCrop2ML
  license: Cecill-c License
  summary: PyCrop2ML Python library.

