{% set data = load_setup_py_data() %}

package:
  name: pycropml
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: {{PYTHON}} setup.py install 

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
  run:
    - python {{PY_VER}}
    - cython
    - path
    - {{ pin_compatible('numpy',    max_pin='x.x') }}
    - pyyaml
    - six
    - networkx
    - unyt
    - nbformat
    - ipython
    - nbsphinx
    #- graphviz
    #- pydot
    - xmlformatter
    #- openalea.core
    - antlr4-python3-runtime ==4.8


test:
  commands:
    - cyml -h


about:
  home: https://github.com/AgriculturalModelExchangeInitiative/PyCrop2ML
  license: Cecill-c License
  summary: PyCrop2ML Python library.

