package:
  name: pycropml
  version: 2.2.0

source:
  path: ..

build:
  #noarch: python  [unix]
  number: 0
  preserve_egg_dir: True
  
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - antlr4-python3-runtime ==4.8
    - cython >=0.29.37,<3
    - xmlformatter
    - numpy   >=2.0
    - pyyaml
    - networkx
    - unyt
    - nbformat
    - ipython
    - nbsphinx
    - graphviz
    - pydot
    - pandas
    - openalea.core



test:
  imports:
    - pycropml

  commands:
    - cyml -h
    - cyml-check-composition --help

about:
  home: https://github.com/AgriculturalModelExchangeInitiative/PyCrop2ML
  license: Cecill-c 
  summary: PyCrop2ML Python library.

