{% set data = load_file_data('../pyproject.toml') %}
{% set version = data.get('project', {}).get('version', '2.2.0') %}

package:
  name: pycropml
  version: {{ 'version' }}

source:
  path: ..

build:
  #noarch: python  [unix]
  preserve_egg_dir: True
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry: 
    - cyml = pycropml.main:main
    - cyml-check-composition = pycropml.transpiler.antlr_py.validate_composition:main


requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - antlr4-python3-runtime ==4.8
    - cython >=0.29.37,<3
    - xmlformatter
    - numpy   >=2.0
    - pyyaml
    - networkx
    - unyt
    - nbformat
    - ipython
    - nbsphinx
    - graphviz
    - pydot
    - openalea.core



test:
  imports:
    - pycropml
  commands:
    - cyml -h

about:
  home: https://github.com/AgriculturalModelExchangeInitiative/PyCrop2ML
  license: Cecill-c 
  summary: PyCrop2ML Python library.

