{% set data = load_setup_py_data() %}

package:
  name: pycropml
  version: {{ data.get('version') }}

source:
  path: ..

build:
  #noarch: python  [unix]
  preserve_egg_dir: True
  number: 0
  script: {{PYTHON}} setup.py install 
  entry: 
    - cyml = pycropml.main:main

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
  run:
    - python {{PY_VER}}
    - antlr4-python3-runtime  ==4.8
    - cython ==0.29.21
    - xmlformatter
    - path
    - numpy ==1.16.6
    - pyyaml
    - six
    - networkx
    - unyt
    - nbformat
    - ipython
    - nbsphinx
    - graphviz
    - pydot
    - openalea.core


#test:
#  imports:
#    - pycropml

about:
  home: https://github.com/AgriculturalModelExchangeInitiative/PyCrop2ML
  license: Cecill-c License
  summary: PyCrop2ML Python library.

